### ISSUE TITLE
Colbert-X Checkpoints Available?

### ISSUE THREAD

**Issue by Amad881** [hltcoe/ColBERT-X#6]
Are there Colbert-X checkpoints available or is retraining necessary?

**Comment by eugene-yang** [comment]
Hi! I believe you have also reached out to me through email. For the sake of people on GitHub, I'm summarizing my response here. 

There is one MLIR model that we released for the NeuCLIR MLIR task. https://huggingface.co/eugene-yang/plaidx-xlmr-large-mlir-neuclir
This model is compatible with the current codebase.
If you are also interested in CLIR models, we released a set of models here: https://huggingface.co/collections/hltcoe/translate-distill-659a11e0a7f2d2491780a6bb

I am in the process of pushing a new version of the code in our github repo. 
It will have a little bit of breaking changes in the indexing process.
The working branch for these changes is in [`publish-test`](https://github.com/hltcoe/ColBERT-X/tree/publish-test). 
There is also a pypi version 0.21.1 that uses this working branch. https://pypi.org/project/PLAID-X/
In the next week or so, I will start pushing changes to this branch and eventually merge to the `plaid-x` branch. 

For using the package, we put together a tutorial at SIGIR 2023 and the material are at: https://github.com/hltcoe/clir-tutorial. 
We have a jupyter notebook for demoing how to use PLAID.

**Comment by santoshTYSS** [comment]
Hi @eugene-yang, The above HuggingFace link seems to be broken. Can you please point out to Colbert-X (ZS) i.e initialised with XLM-R and fine-tuned on ms-marco English developed as part of https://arxiv.org/pdf/2201.08471

**Comment by eugene-yang** [comment]
Oops, I moved the collection and forgot to update the link. It is fixed now. 

As for the zeroshot ColBERT-X model, we did not release that specific model but there is one in a very similar setting. 
Instead of using the msmarco training triples, this checkpoint used distillation to train the model. https://huggingface.co/hltcoe/plaidx-large-eng-tdist-mt5xxl-engeng
It was trained with only English data in the pipeline.
